//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgeGroupRequirment
    {
        public int Id { get; set; }
        public short GoldCount { get; set; }
        public short BronzeCount { get; set; }
        public int AgeGroupId { get; set; }
        public short Sex { get; set; }
        public short SilverCount { get; set; }
    
        public virtual AgeGroup AgeGroup { get; set; }
    }
}
