//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GtoEventPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GtoEventPlayer()
        {
            this.GtoEventPlayerRecords = new HashSet<GtoEventPlayerRecord>();
        }
    
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int GtoEventId { get; set; }
    
        public virtual GtoEvent GtoEvent { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GtoEventPlayerRecord> GtoEventPlayerRecords { get; set; }
    }
}
