//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GtoEventPlayerRecord
    {
        public int Id { get; set; }
        public int GtoEventPlayerId { get; set; }
        public int GtoEventTestId { get; set; }
        public string TestValue { get; set; }
        public GTO.Model.Enums.ResultRank ResultRank { get; set; }
    
        public virtual GtoEventPlayer GtoEventPlayer { get; set; }
        public virtual GtoEventTest GtoEventTest { get; set; }
    }
}
