//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO.Model.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GtoDatabaseContext : DbContext
    {
        public GtoDatabaseContext()
            : base("name=GtoDatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GtoEvent> GtoEvents { get; set; }
        public virtual DbSet<GtoEventPlayer> GtoEventPlayers { get; set; }
        public virtual DbSet<GtoEventPlayerRecord> GtoEventPlayerRecords { get; set; }
        public virtual DbSet<GtoEventTest> GtoEventTests { get; set; }
        public virtual DbSet<Judge> Judges { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestGroup> TestGroups { get; set; }
        public virtual DbSet<AgeGroup> AgeGroups { get; set; }
    }
}
