//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestGroup
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public Nullable<double> Bronze { get; set; }
        public Nullable<double> Serebro { get; set; }
        public Nullable<double> Gold { get; set; }
        public short Sex { get; set; }
        public int AgeGroupId { get; set; }
        public GTO.Model.Enums.TestType TestType { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual AgeGroup AgeGroup { get; set; }
    }
}
