//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTO.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestGroup
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public short AgeMax { get; set; }
        public short AgeMin { get; set; }
        public Nullable<double> Bronze { get; set; }
        public Nullable<double> Serebro { get; set; }
        public Nullable<double> Gold { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
